name: Mypy
on: workflow_dispatch

jobs:
  mypy_py3:
    name: Mypy check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install Dependencies
        run: |
          uv sync --locked --group dev
      - name: mypy
        run: |
          make mypy
